#!/usr/bin/env ruby

product = `dmidecode -s system-product-name`.chomp
if product != 'Aspire A315-51'
  puts "Not running on Aspire 3"
  exit 0
end

line = IO.popen(['efibootmgr', '-v'], &:readlines)
         .grep(%r{/IPv4})
         .first

unless line
  $stderr.puts "No netboot entry"
  exit 1
end

if /^Boot(?<bootnum>\d{4})/ =~ line
  exec('efibootmgr', '-n', bootnum)
else
  $stderr.puts "Malformed line: #{line.chomp}"
  exit 1
end
