source 'https://rubygems.org'

gem 'hocho', git: 'https://github.com/sorah/hocho'
#gem 'hocho', path: '~/git/github.com/sorah/hocho'
gem 'hocho-ec2', git: 'https://github.com/sorah/hocho-ec2'
#gem 'hocho-ec2', path: '~/git/github.com/sorah/hocho-ec2'
gem 'itamae-secrets'
